AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  InstanceName:
    Type: String
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c7217cdde317cfec  # Replace with a valid AMI ID
      InstanceType: t2.micro  # Replace with the desired instance type
      KeyName: devops_lab_key_pair   # Replace with your key pair name
      SubnetId: subnet-0da9e04435a068a7f
      SecurityGroupIds:
        - sg-01426431942028228
      Tags:
        - Key: Name
          Value: !Ref InstanceName
